### ISSUE TITLE
将 cloud-native-bot 添加至 envoy team

### ISSUE THREAD

**Issue by 3ks** [cloudnativeto/envoy#17]
## envoy 任务管理

envoy 翻译工作目前使用 [issue-man](https://github.com/3ks/issue-man) 管理任务（issue），相关使用说明请结合 [Envoy 中文文档翻译指导手册](https://github.com/cloudnativeto/envoy/tree/zh/docs/root) 查看。

维护人：@3ks

申请：将 @cloud-native-bot 添加至 https://github.com/orgs/cloudnativeto/teams/envoy

行为说明：机器人会创建、修改 [envoy](https://github.com/cloudnativeto/envoy) 下的 label、issue。

经办人：@stevensu1977 @rootsongjc

**Comment by stevensu1977** [comment]
issue, issue comments, labels 权限已经打开
