### ISSUE TITLE
docs/root/term.md

### ISSUE THREAD

**Issue by redzippo1** [cloudnativeto/envoy#480]
*Title*: *常用词汇中缺少 overview 一词*

*Description*:
>经小马哥指点，该词应翻译为“概览”

**Comment by majinghe** [comment]
@redzippo1 这个你直接 提个PR，把那个词汇加进去即可。

**Comment by redzippo1** [comment]
> @redzippo1 这个你直接 提个PR，把那个词汇加进去即可。

好的
